platform :ios,"7.0"
pod 'MBProgressHUD'
pod 'Reachability', '~> 3.2'
pod 'Toast', '~> 2.4'
pod 'ZipArchive', '~> 1.4.0'
pod 'FDFullscreenPopGesture', '~> 1.0'
pod 'JSONKit', '~> 1.5pre'
pod 'EGOTableViewPullRefresh', '~> 0.1.0'
pod 'SDWebImage', '~> 3.7.2'
pod 'SIAlertView', '~> 1.3'
pod 'JDStatusBarNotification', '~> 1.5.2'

